### ISSUE TITLE
Suggest/ design a JSON payload schema.

### ISSUE THREAD

**Issue by karthik2603-theBrogrammer** [dscpesu/resume-latex#5]
- Make a folder 'schema' with <file_name>.json
- The json resume information schema coming from client to flask server
- this is necessary for contributors to understand the data they are working with.

**Comment by FreakQnZ** [comment]
I have thought of adding 6 main sections.
 
Personal Infromation
Education
Skills/languages/Technologies
Experiences
Awards and certifications
Projects

We will again dive into these sections to add more information.

Do we wait for the frontend first to be completed and then proceed with this?

**Comment by karthik2603-theBrogrammer** [comment]
finishing this task will give the frontend devs a better idea hence this a must first.

**Comment by 0xIcarus** [comment]
Have sent PR please to check it out.
